// File generated by manual configuration based on provided Firebase info.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0ipKuvjeEZgIPXqK7M9sc-qnyAkfv9bk',
    appId: '1:23918025468:web:206faa9989c7d856309579',
    messagingSenderId: '23918025468',
    projectId: 'sr-ghani',
    authDomain: 'sr-ghani.firebaseapp.com',
    storageBucket: 'sr-ghani.firebasestorage.app',
    measurementId: 'G-YXLS9SFLN1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxtTJZWAZKqyi2SraI061mONieeSYTknM',
    appId: '1:23918025468:android:ff8724a803c44904309579',
    messagingSenderId: '23918025468',
    projectId: 'sr-ghani',
    storageBucket: 'sr-ghani.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8FL7IDwus7HiwxntyK0UAbZX5dNUiIuo',
    appId: '1:23918025468:ios:83f9652e8bcf00ba309579',
    messagingSenderId: '23918025468',
    projectId: 'sr-ghani',
    storageBucket: 'sr-ghani.firebasestorage.app',
    iosBundleId: 'com.app.sr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0ipKuvjeEZgIPXqK7M9sc-qnyAkfv9bk',
    appId: '1:23918025468:web:206faa9989c7d856309579',
    messagingSenderId: '23918025468',
    projectId: 'sr-ghani',
    authDomain: 'sr-ghani.firebaseapp.com',
    storageBucket: 'sr-ghani.firebasestorage.app',
    measurementId: 'G-YXLS9SFLN1',
  );
}
